# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc/Zybo-Z7-Master.xdc

# Block Designs: bd/design_irq/design_irq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_irq || ORIG_REF_NAME==design_irq} -quiet] -quiet

# IP: bd/design_irq/ip/design_irq_processing_system7_0_0/design_irq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_irq_processing_system7_0_0 || ORIG_REF_NAME==design_irq_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_irq/ip/design_irq_axi_gpio_0_0/design_irq_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_irq_axi_gpio_0_0 || ORIG_REF_NAME==design_irq_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_irq/ip/design_irq_axi_gpio_1_0/design_irq_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_irq_axi_gpio_1_0 || ORIG_REF_NAME==design_irq_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_irq/ip/design_irq_xbar_0/design_irq_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_irq_xbar_0 || ORIG_REF_NAME==design_irq_xbar_0} -quiet] -quiet

# IP: bd/design_irq/ip/design_irq_ps7_0_axi_periph_0/design_irq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_irq_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_irq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_irq/ip/design_irq_rst_ps7_0_50M_0/design_irq_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_irq_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_irq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_irq/ip/design_irq_auto_pc_0/design_irq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_irq_auto_pc_0 || ORIG_REF_NAME==design_irq_auto_pc_0} -quiet] -quiet

# XDC: /mnt/media/Zybo_Projects/Zybo_Interrupts/Zybo_Interrupts.gen/sources_1/bd/design_irq/design_irq_ooc.xdc
