# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/media/Zybo_Projects/Zybo_Interrupts/Zybo_Interrupts.srcs/sources_1/bd/design_irq/ip/design_irq_xbar_0/design_irq_xbar_0.xci
# IP: The module: 'design_irq_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/media/Zybo_Projects/Zybo_Interrupts/Zybo_Interrupts.gen/sources_1/bd/design_irq/ip/design_irq_xbar_0/design_irq_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_irq_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/media/Zybo_Projects/Zybo_Interrupts/Zybo_Interrupts.srcs/sources_1/bd/design_irq/ip/design_irq_xbar_0/design_irq_xbar_0.xci
# IP: The module: 'design_irq_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/media/Zybo_Projects/Zybo_Interrupts/Zybo_Interrupts.gen/sources_1/bd/design_irq/ip/design_irq_xbar_0/design_irq_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_irq_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
